### ISSUE TITLE
How to achieve autobound action creators with a store?

### ISSUE THREAD

**Issue by zusamann** [feathersjs/feathers-redux#21]
Hi, firstly thanks for this great addition to the ecosystem.

Currently as per the documentation, the `reduxifiedServices` return a plain actions object that has to be dispatched with the `store.dispatch` which is pretty standard vanilla redux.

```js
import reduxifyServices from 'feathers-redux';
const feathersClient = feathers(). ...;

// Create Redux actions and reducers for Feathers services
const services = reduxifyServices(feathersClient, ['users', 'messages']);

// Configure Redux store & reducers
export default combineReducers({
  users: services.users.reducer,
  messages: services.messages.reducer,
});

// Feathers service calls may now be dispatched.
store.dispatch(services.messages.get('557XxUL8PalGMgOo'));
store.dispatch(services.messages.find());
store.dispatch(services.messages.create({ text: 'Hello!' }));
```

But if one were looking to bind them to a store dispatch method so that the flow can simply be:
```js
services.messages.get('557XxUL8PalGMgOo') // both creates and dispatches the redux action
// and not
store.dispatch(services.messages.get('557XxUL8PalGMgOo'));
```

In what would be a standard redux implementation this can be achieved like so:
source: http://redux.js.org/docs/api/bindActionCreators.html
```js
// action creators

export function addTodo(text) {
  return {
    type: 'ADD_TODO',
    text
  }
}

export function removeTodo(id) {
  return {
    type: 'REMOVE_TODO',
    id
  }
}
```
```js
import { bindActionCreators } from 'redux'
import * as TodoActionCreators from './TodoActionCreators'

....
 render() {
    // Injected by react-redux:
    let { todos, dispatch } = this.props

    // Here's a good use case for bindActionCreators:
    // You want a child component to be completely unaware of Redux.

    let boundActionCreators = bindActionCreators(TodoActionCreators, dispatch)
....
```

Wondering how can this be achieved with the output of `reduxifiedServices` as it stands right now, and is it possible to add a feature which can take a dispatch function ( optional ofcourse ) and autobind it to all action creators.

**Comment by zusamann** [comment]
Ok I was able to achieve something by cherry picking the output of the reduxified services, let me know if it needs some corrections.

```js
// reducers.js

import { combineReducers } from 'redux';
import reduxifyServices from 'feathers-redux';
import client from 'utils/client';

const serviceMap = {
  'auth/login': 'auth',
  'db/users': 'users'
};

export const rawServices = reduxifyServices(client, serviceMap);
const _f = {};
Object.keys(rawServices).forEach(_s => (_f[_s] = rawServices[_s].reducer));

export default combineReducers({ ..._f });
```
```js
// store.js

import { createStore, bindActionCreators } from 'redux';
import { pick, omit, mapObjIndexed } from 'ramda';

import rootReducer, { rawServices } from 'store/reducers';

const store = createStore(rootReducer);

// ignoring 'on' and 'reducer' keys in the output as they don't seem to be action creators
const actions = [
  'find',
  'get',
  'create',
  'update',
  'patch',
  'remove',
  'reset',
  'store'
];

const bindDispatch = (_svc, _dispatch) =>

  // map over the services object for each service
  mapObjIndexed(val => ({

    //  destructure in bound action creators that are picked
    ...bindActionCreators(pick(actions, val), _dispatch),

   // destructure in rest of the keys that were not targeted as action creators
    ...omit(actions, val)
  }))(_svc);

// call the bind dispatch function on raw services with the store.dispatch method 
export const services = bindDispatch(rawServices, store.dispatch);

export default store;
```
```js
// App.js

import { services } form store;

// voila!
const creds = { ... }
services.auth.create(creds) 
```

Let me know if this method is correct, I couldn't find a better way to do it, the ideal way would've been to pass the `dispatch` method to the `reduxifyServices` itself in the `options` object maybe. But since the `dispatch` comes from `store` and `store` needs the `rootReducer` that comes from the output of the `reduxifyServices` it would create a cyclical dependency **ouch**.

So for now it would work best with transforming the output of `reduxifyServices`.

If this seems palatable, then can we please add it to the readme as a recipe of sort, since it could be helpful. @eddyystop

**Comment by eddyystop** [comment]
That's a neat addition. Finding `dispatch` can be such a pain.

Perhaps you can take a PR containing a method that does the above? An updated README (in which you give yourself a shout) and tests would be extra.

**Comment by zusamann** [comment]
Just to be clear you can't really pass in the dispatch method while calling `reduxifyServices` the first time, because you need an instance of store, but the instance of store needs the reducers from the `reduxifiedServices` hence the cyclical dependency.

So at best it would be a helper function like what `getServiceStatus` is currently. And the final flow would look like so:

- Create the `reduxifiedServices`
- Create the `store`
- Bind the `reduxifiedServices` with `store.dispatch`

Also this would make `redux` a dependency as the `bindActionCreators` function comes from there.

If you think all of this is fine, then I'll try and make a PR out of these.

**Comment by eddyystop** [comment]
Yes, I did mean a separate call.

I was thinking you could pass in `services` from `services = reduxifyServices(app, serviceNames, options)` and bind all the methods for all the services.

**Comment by zusamann** [comment]
Cool, will make a PR and submit.

**Comment by petermikitsh** [comment]
Just ran into this myself. I'm using react-redux and having to bind the action creators. This functionality would be a fantastic addition to the library.

**Comment by eddyystop** [comment]
@zusamann Any progress?

**Comment by zusamann** [comment]
hi @eddyystop, sorry not able to create a PR for this yet, will do so shortly, however the solution is already written above, so that can be used in the meantime

**Comment by eddyystop** [comment]
I'm closing this in favor of the discussion happening in PR #25 mentioned above.
