### ISSUE TITLE
The State is not reactive

### ISSUE THREAD

**Issue by radiegtya** [feathersjs/feathers-redux#23]
My redux state is not reactively changed after find data..

```javascript
import React, { Component } from 'react';
import {StyleSheet, Text, View} from 'react-native';
import { connect } from 'react-redux';

class App extends Component {
  componentDidMount(){
    //find posts here
    this.props.handleFind()
  }

  render() {
    const { getServicesStatus, reduxState: { posts } } = this.props;
    console.log(posts)
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
            {/* posts printed here is not reactively changed */}
          {posts.data ? JSON.stringify(posts.data, null, 2) : 'no data'}
        </Text>
      </View>
    );
  }
}

const mapStateToProps = (state) => ({
  reduxState: state,
});

const mapDispatchToProps = (dispatch, { services }) => ({
  handleFind: () => {
    dispatch(services.posts.find());
  },
});

export default connect(mapStateToProps, mapDispatchToProps)(App);
```

### Expected behavior

State should reactively changed after componentDidMount trigger dispatch..

### Actual behavior

State not reactively changed after componentDidMount trigger dispatch

<img width="548" alt="feathers_redux_bug" src="https://user-images.githubusercontent.com/2161622/29209534-48460f50-7eb9-11e7-82ee-2bae26921077.png">
the action had been dispatched, but state not changed

<img width="320" alt="feathers_redux_bug2" src="https://user-images.githubusercontent.com/2161622/29209586-8461981a-7eb9-11e7-8c07-bec24e562064.png">
the value of reduxState not changed

### System configuration

**Module versions** (especially the part that's not working):
"feathers-redux": "0.0.3"

**NodeJS version**:
v7.7.3

**Operating System**:
Mac OSx

**React Native Version**:
"react-native": "0.47.1"

**Comment by eddyystop** [comment]
The intent of the repo is to connect Feathers service calls you make to the redux store.

Are you asking for the repo to redo those Feathers calls?

**Comment by radiegtya** [comment]
No, i just need to get the data from state after dispatch an action. How to get the data that is fetched, from the redux state?

**Comment by zusamann** [comment]
dude, fetching data from the state has nothing to do with this library, you should read redux and react-redux documentation for that

http://redux.js.org/docs/api/Store.html#getState
http://redux.js.org/docs/api/Store.html#subscribe
https://github.com/reactjs/react-redux/blob/master/docs/api.md#examples

**Comment by ucokfm** [comment]
it seems result of 'find' action is in state.posts.queryResult.data and result of 'get' action is in state.posts.data and be sure to null checking queryResult before access to queryResult.data

**Comment by radiegtya** [comment]
@ucokfm : yeah true, the find action is at state.posts.queryResult.data but it still not reactive after all. The value still using the old state rather than nextState. 
Btw can u give the working example??

Thanks

**Comment by radiegtya** [comment]
here is code as @ucokfm suggested, still after "SERVICES_POSTS_FIND_FULFILLED" dispatched, the state is not changed.

```javascript
import React, { Component } from 'react';
import {StyleSheet, Text, View} from 'react-native';
import { connect } from 'react-redux';

class App extends Component {

  componentDidMount(){
    this.props.handleFind()
  }

  render() {
    const { posts } = this.props;
    console.log(posts)
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          {posts.data ? JSON.stringify(posts.data) : 'no data'}
        </Text>
      </View>
    );
  }
}

const mapStateToProps = (state) => ({
  posts: state.posts.queryResult ? state.posts.queryResult.data : [],  //I DID NULL CHECK HERE
});

const mapDispatchToProps = (dispatch, { services }) => ({
  handleFind: () => {
    dispatch(services.posts.find({}, 'posts'));
  },
});

export default connect(mapStateToProps, mapDispatchToProps)(App);
```

action dispatch 'SERVICES_POSTS_FIND_PENDING' print out the state, but unfortunately 'SERVICES_POSTS_FIND_FULFILLED' did not print the state again. Look at pict below

<img width="553" alt="bug_feathers_redux_12aug" src="https://user-images.githubusercontent.com/2161622/29239724-e0138734-7f7e-11e7-91a7-d6239cfa9fe0.png">

What am I doing wrong???

**Comment by radiegtya** [comment]
[Closed]
I know the culprit, thanks @ucokfm for the answer. My Code above worked, but strangely only the console.log not working.. Anyway it printed out when use it on component..

**Comment by ucokfm** [comment]
```import React, { Component } from 'react';
import {StyleSheet, Text, View} from 'react-native';
import { connect } from 'react-redux';

class App extends Component {

  componentDidMount(){
    this.props.handleFind()
  }

  render() {
    const { posts } = this.props;
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          {posts.queryResult && posts.queryResult.data ? JSON.stringify(posts.queryResult.data) : 'no data'}
        </Text>
      </View>
    );
  }
}

const mapStateToProps = (state) => ({
  posts: state.posts,
});

const mapDispatchToProps = (dispatch, { services }) => ({
  handleFind: () => {
    dispatch(services.posts.find());
  },
});

export default connect(mapStateToProps, mapDispatchToProps)(App);
```

this is my version of your code, may be can be also useful

**Comment by eddyystop** [comment]
Wow. Thanks everyone for chipping in. It appears this repo has a community.
