### ISSUE TITLE
Data key set to null whilst loading/saving

### ISSUE THREAD

**Issue by Jackleberry** [feathersjs/feathers-redux#31]
I noticed that when saving/loading the data key is set to null and then is set appropriately when the promise resolves. 

See here:
https://github.com/feathersjs/feathers-redux/blob/master/src/index.js#L105

This causes things to flash away for a sec in my app. I would like to change that behaviour to be the same as queryResult where the previous value is there until updated when the promise resolves.

See here:
https://github.com/feathersjs/feathers-redux/blob/master/src/index.js#L106

I'm happy to make a PR, just wanted to see if this is the kind of behaviour that people want?

**Comment by eddyystop** [comment]
Such flashing should be eliminated. I'm open to a PR. The PR would have to handle a failure as well.

**Comment by Jackleberry** [comment]
Here is the PR: https://github.com/feathersjs/feathers-redux/pull/32

I think the failure scenario is already handled appropriately when the promise is rejected.

**Comment by eddyystop** [comment]
Thanks!
