### ISSUE TITLE
Server side rendering, store empty.

### ISSUE THREAD

**Issue by JigsWeb** [feathersjs/feathers-redux#34]
Hello, 

The store is empty so I need to make a condition in my components who need records.

`this.heroes = this.heroesStore ? this.heroesStore.records : []`

Do you have another solution ?

(I use react-universally boilerplate)

**Comment by eddyystop** [comment]
As far as I can see, the store would be empty only if no dispatch was posted.

**Comment by JigsWeb** [comment]
So I dispatch a store action when I create the store

`store.dispatch(service.hero.strore({ connected: false, last: {}, records: [] }))`

It's working, but I want to know if a cleaner way is possible.

And why store is null ? Where is the problem if store is not null without dispatching ?

Thanks for your patience.

**Comment by eddyystop** [comment]
The initial store is null because its easier to check that a value is null then to check that its an empty object. I expect you have to take special action for an empty store in any case.

**Comment by JigsWeb** [comment]
Ok ok thanks for your answer ! 👍
