### ISSUE TITLE
isError cleared incorrectly

### ISSUE THREAD

**Issue by Sicria** [feathersjs/feathers-redux#59]
https://github.com/feathers-plus/feathers-redux/blob/master/src/index.js#L137

This causes flashing when the error is cleared and the user is retrying a request after the previous request has failed.

It would be good if the error is only cleared on success or set again on failure.

Since the ``isError`` means that the previous request has failed, it should still show that the previous request has failed until the next request has either succeeded or failed.

**Comment by eddyystop** [comment]
I'm understand your point and I'm sympathetic to the issue.

The repo handles async actions as is commonly expected in Redux. The screen flicker is a side effect.

I don't see making a breaking change to the repo which conflates async actions with a UI side effect. Perhaps its best to handle this as a Redux side effect.

Feel free to reopen this issue if you have additional comments.
